version: '3'
services:
  localnet:
    image: solanalabs/solana:stable
    ports:
      - "8899:8899" # JSONRPC over HTTP
      - "8900:8900" # JSONRPC over Websockets
  
  solana-cli:
    build:
      context: ./solanaCli
    tty: true
    command: 172.17.0.1 8899 true
    volumes:
      - /home/volker/repos/solanaPlayground/reactApp/app/src/keypair:/home/keypair:rw