[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
game_record = "4STVHcERmNuyqZK2254ZAdNDVsikgx9oTTH5sjhCc727"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/volker/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
